### ISSUE TITLE
Failing against wxWidgets 2.9.3

### ISSUE THREAD

**Issue by simendsjo** [afb/wxd#7]
Successfully build wxD, although I had to comment out several methods that didn't exist - strange as you've tried it on 2.9.2..
Examples are compiled, but I get an error when trying to open them:

$ ./Minimal 
./src/common/strconv.cpp(1210): assert "Assert failure" failed in FromWChar(): trying to encode undefined Unicode character
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()
(process:27413): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()
(process:27413): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion `G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()
(process:27413): GLib-GObject-CRITICAL **: g_type_interface_add_prerequisite: assertion `G_TYPE_IS_INTERFACE (interface_type)' failed
(process:27413): GLib-CRITICAL **: g_once_init_leave: assertion `initialization_value != 0' failed
(process:27413): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion `G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(process:27413): GLib-GObject-CRITICAL **: /build/buildd/glib2.0-2.30.0/./gobject/gtype.c:2708: You forgot to call g_type_init()

Compiled using gdc 4.6.
I don't know any GTK or wxWidgets, so I have no idea whats going on here.

**Comment by afb** [comment]
Moving back to sourceforge, try there for help
